name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # כאן אנחנו משאירים את ה-Username ידנית או דרך Secret
          # אם ה-Secret עושה בעיות, פשוט תכתוב כאן את השם שלך במירכאות, למשל: "shaul123"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # כאן שיניתי: תחליף את המילה shaul בשם המשתמש האמיתי שלך ב-Docker Hub
          tags: shaulbgc/my-flask-app:latest
